export const states = [
  {
    name: "Alabama",
    abbreviation: "AL",
    territory: false,
    capital: "Montgomery",
  },
  {
    name: "Alaska",
    abbreviation: "AK",
    territory: false,
    capital: "Juneau",
  },
  {
    name: "American Samoa",
    abbreviation: "AS",
    territory: true,
    capital: "Pago Pago",
  },
  {
    name: "Arizona",
    abbreviation: "AZ",
    territory: false,
    capital: "Phoenix",
  },
  {
    name: "Arkansas",
    abbreviation: "AR",
    territory: false,
    capital: "Little Rock",
  },
  {
    name: "California",
    abbreviation: "CA",
    territory: false,
    capital: "Sacramento",
  },
  {
    name: "Colorado",
    abbreviation: "CO",
    territory: false,
    capital: "Denver",
  },
  {
    name: "Connecticut",
    abbreviation: "CT",
    territory: false,
    capital: "Hartford",
  },
  {
    name: "Delaware",
    abbreviation: "DE",
    territory: false,
    capital: "Dover",
  },
  {
    name: "District Of Columbia",
    abbreviation: "DC",
    territory: false,
    capital: "",
  },
  {
    name: "Federated States Of Micronesia",
    abbreviation: "FM",
    territory: true,
    capital: "Palikir",
  },
  {
    name: "Florida",
    abbreviation: "FL",
    territory: false,
    capital: "Tallahassee",
  },
  {
    name: "Georgia",
    abbreviation: "GA",
    territory: false,
    capital: "Atlanta",
  },
  {
    name: "Guam",
    abbreviation: "GU",
    territory: true,
    capital: "Hagåtña",
  },
  {
    name: "Hawaii",
    abbreviation: "HI",
    territory: false,
    capital: "Honolulu",
  },
  {
    name: "Idaho",
    abbreviation: "ID",
    territory: false,
    capital: "Boise",
  },
  {
    name: "Illinois",
    abbreviation: "IL",
    territory: false,
    capital: "Springfield",
  },
  {
    name: "Indiana",
    abbreviation: "IN",
    territory: false,
    capital: "Indianapolis",
  },
  {
    name: "Iowa",
    abbreviation: "IA",
    territory: false,
    capital: "Des Moines",
  },
  {
    name: "Kansas",
    abbreviation: "KS",
    territory: false,
    capital: "Topeka",
  },
  {
    name: "Kentucky",
    abbreviation: "KY",
    territory: false,
    capital: "Frankfort",
  },
  {
    name: "Louisiana",
    abbreviation: "LA",
    territory: false,
    capital: "Baton Rouge",
  },
  {
    name: "Maine",
    abbreviation: "ME",
    territory: false,
    capital: "Augusta",
  },
  {
    name: "Marshall Islands",
    abbreviation: "MH",
    territory: true,
    capital: "Majuro",
  },
  {
    name: "Maryland",
    abbreviation: "MD",
    territory: false,
    capital: "Annapolis",
  },
  {
    name: "Massachusetts",
    abbreviation: "MA",
    territory: false,
    capital: "Boston",
  },
  {
    name: "Michigan",
    abbreviation: "MI",
    territory: false,
    capital: "Lansing",
  },
  {
    name: "Minnesota",
    abbreviation: "MN",
    territory: false,
    capital: "Saint Paul",
  },
  {
    name: "Mississippi",
    abbreviation: "MS",
    territory: false,
    capital: "Jackson",
  },
  {
    name: "Missouri",
    abbreviation: "MO",
    territory: false,
    capital: "Jefferson City",
  },
  {
    name: "Montana",
    abbreviation: "MT",
    territory: false,
    capital: "Helena",
  },
  {
    name: "Nebraska",
    abbreviation: "NE",
    territory: false,
    capital: "Lincoln",
  },
  {
    name: "Nevada",
    abbreviation: "NV",
    territory: false,
    capital: "Carson City",
  },
  {
    name: "New Hampshire",
    abbreviation: "NH",
    territory: false,
    capital: "Concord",
  },
  {
    name: "New Jersey",
    abbreviation: "NJ",
    territory: false,
    capital: "Trenton",
  },
  {
    name: "New Mexico",
    abbreviation: "NM",
    territory: false,
    capital: "Santa Fe",
  },
  {
    name: "New York",
    abbreviation: "NY",
    territory: false,
    capital: "Albany",
  },
  {
    name: "North Carolina",
    abbreviation: "NC",
    territory: false,
    capital: "Raleigh",
  },
  {
    name: "North Dakota",
    abbreviation: "ND",
    territory: false,
    capital: "Bismarck",
  },
  {
    name: "Northern Mariana Islands",
    abbreviation: "MP",
    territory: true,
    capital: "Saipan",
  },
  {
    name: "Ohio",
    abbreviation: "OH",
    territory: false,
    capital: "Columbus",
  },
  {
    name: "Oklahoma",
    abbreviation: "OK",
    territory: false,
    capital: "Oklahoma City",
  },
  {
    name: "Oregon",
    abbreviation: "OR",
    territory: false,
    capital: "Salem",
  },
  {
    name: "Palau",
    abbreviation: "PW",
    territory: true,
    capital: "Ngerulmud",
  },
  {
    name: "Pennsylvania",
    abbreviation: "PA",
    territory: false,
    capital: "Harrisburg",
  },
  {
    name: "Puerto Rico",
    abbreviation: "PR",
    territory: true,
    capital: "San Juan",
  },
  {
    name: "Rhode Island",
    abbreviation: "RI",
    territory: false,
    capital: "Providence",
  },
  {
    name: "South Carolina",
    abbreviation: "SC",
    territory: false,
    capital: "Columbia",
  },
  {
    name: "South Dakota",
    abbreviation: "SD",
    territory: false,
    capital: "Pierre",
  },
  {
    name: "Tennessee",
    abbreviation: "TN",
    territory: false,
    capital: "Nashville",
  },
  {
    name: "Texas",
    abbreviation: "TX",
    territory: false,
    capital: "Austin",
  },
  {
    name: "Utah",
    abbreviation: "UT",
    territory: false,
    capital: "Salt Lake City",
  },
  {
    name: "Vermont",
    abbreviation: "VT",
    territory: false,
    capital: "Montpelier",
  },
  {
    name: "Virgin Islands",
    abbreviation: "VI",
    territory: true,
    capital: "Charlotte Amalie",
  },
  {
    name: "Virginia",
    abbreviation: "VA",
    territory: false,
    capital: "Richmond",
  },
  {
    name: "Washington",
    abbreviation: "WA",
    territory: false,
    capital: "Olympia",
  },
  {
    name: "West Virginia",
    abbreviation: "WV",
    territory: false,
    capital: "Charleston",
  },
  {
    name: "Wisconsin",
    abbreviation: "WI",
    territory: false,
    capital: "Madison",
  },
  {
    name: "Wyoming",
    abbreviation: "WY",
    territory: false,
    capital: "Cheyenne",
  },
];
